main = "wrangler.js"
name = "loopholelabs-io-docs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".open-next/assets", binding = "ASSETS", experimental_serve_directly = false }

[vars]
NEXT_PUBLIC_POSTHOG_KEY = "phc_ROI4hShMvIq47MpdUs6ezbtncfQhqkRCebezH4qBUEr"
NEXT_PUBLIC_POSTHOG_HOST = "https://data.loopholelabs.io"